### PR TITLE
convert_qcow2_ova.py fails for relative tmp directory path. issue #30

### LINKED ISSUE #30: convert_qcow2_ova.py fails for relative tmp directory path
Script fails for a relative temporary directory path

```
[root@rhel8]# ./convert_qcow2_ova.py -u ./rhcos-46.ppc64le.qcow2.gz -n rhos46 -d coreos -U <*****> n -P <*******> -s 5  -O <******> -T ./
Extracting gz image...
Converting to raw ....
command: qemu-img convert -f qcow2 -O raw ./tmphdvzlf2t/rhcos-46.ppc64le.qcow2  ./tmphdvzlf2t/image/rhcos-46.ppc64le
Resizing image ....
command: qemu-img resize ./tmphdvzlf2t/image/rhcos-46.ppc64le 5G
Getting new image size...
Preparing meta data file...
Preparing ovf data file...
Creating ova image...
Compressing ova file...
pigz found in  /usr/bin/pigz  will use pigz for gzip
command: pigz -k -c ./tmphdvzlf2t/rhos46.ova > ./tmphdvzlf2t/rhos46.ova.gz
ERROR: Failed to gzip the file: /bin/sh: ./tmphdvzlf2t/rhos46.ova.gz: No such file or directory

Traceback (most recent call last):
  File "./convert_qcow2_ova.py", line 477, in convert_qcow2_ova
    gzip_gzip(ova_image_file, ova_gz_image_file)
  File "./convert_qcow2_ova.py", line 255, in gzip_gzip
    sys.exit(2)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./convert_qcow2_ova.py", line 541, in <module>
    convert_qcow2_ova(args.imageUrl, args.imageSize, args.imageName, args.imageDist, args.rhnUser, args.rhnPassword, args.osPassword, args.tempDir)
  File "./convert_qcow2_ova.py", line 481, in convert_qcow2_ova
    shutil.rmtree(tmpdir)
  File "/usr/lib64/python3.6/shutil.py", line 477, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib64/python3.6/shutil.py", line 475, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: './tmphdvzlf2t'
[root@rhel8]#
```

### PR DESCRIPTION
**Pull request by sudeeshjohn**
This patch fixes #30 

Signed-off-by: Sudeesh John <sudeeshjohn@in.ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/infra/pull/31#" title="Author self-approved">sudeeshjohn</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Finfra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/infra/blob/master/OWNERS)~~ [sudeeshjohn]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by bpradipt — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/infra/pull/31#pullrequestreview-528816182" title="LGTM">bpradipt</a>*, *<a href="https://github.com/ocp-power-automation/infra/pull/31#" title="Author self-approved">sudeeshjohn</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ocp-power-automation%2Finfra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/infra/blob/master/OWNERS)~~ [bpradipt,sudeeshjohn]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
