### PR TITLE
Added Automation guide to convert qcow2 image to ova

### PR DESCRIPTION
**Pull request by Shilpi-Das1**
Added automation guide to convert qcow2 image to ova
Issue Link: https://github.ibm.com/redstack-power/project-mgmt/issues/655

### CODE REVIEW

**Comment by Shilpi-Das1** [comment]
Tested file convert_qcow2_ova.py with rhel and centos

```
root@shilpi-test:~/infra/scripts/images# ./convert_qcow2_ova.py -u ~/CentOS-8-GenericCloud-8.2.2004-20200611.2.ppc64le.qcow2 -s 1 -n centos -d centos -U <uname> -P <pwd> -O root
Converting to raw ....
Preparing rhel image...
Getting a free loop device ...
probing partition table ...
mounting the loop device ...
Running script ...
shell script : CentOS-8 - AppStream                            0.0  B/s |   0  B     00:00
Retrieving http://public.dhe.ibm.com/software/server/POWER/Linux/yum/download/ibm-power-repo-latest.noarch.rpm
Changing password for user root.
passwd: all authentication tokens updated successfully.

Unmounting all
Freeing up loop device
Resizing image ....
Getting new image size...
Preparing meta data file...
Preparing ovf data file...
Creating ova image...
Compressing ova file...
root@shilpi-test:~/infra/scripts/images# ls
convert_qcow2_ova.py  create_boot_images.py  centos.ova.gz  upload_image.py

root@shilpi-test:~/infra/scripts/images# python3 ./convert_qcow2_ova.py -u ~/rhel-8.2-ppc64le-kvm.qcow2 -s 1 -n rhel-convert -d rhel -U <uname> -P <pwd> -O root
Converting to raw ....
Preparing rhel image...
Getting a free loop device ...
probing partition table ...
mounting the loop device ...
Running script ...
shell script : Rhel-8 - AppStream                            0.0  B/s |   0  B     00:00
Retrieving http://public.dhe.ibm.com/software/server/POWER/Linux/yum/download/ibm-power-repo-latest.noarch.rpm
Changing password for user root.
passwd: all authentication tokens updated successfully.

Unmounting all
Freeing up loop device
Resizing image ....
Getting new image size...
Preparing meta data file...
Preparing ovf data file...
Creating ova image...
Compressing ova file...
root@shilpi-test:~/infra/scripts/images# ls
convert_qcow2_ova.py  create_boot_images.py  centos.ova.gz rhel-convert.ova.gz  test.ova.gz  upload_image.py
```

**Comment by mkumatag** [comment]
@Shilpi-Das1 anything else pending? is it good to merge?

**Comment by Shilpi-Das1** [comment]
> @Shilpi-Das1 anything else pending? is it good to merge?

@mkumatag Nothing pending form my end. It is good to merge

**Comment by mkumatag** [comment]
> > @Shilpi-Das1 anything else pending? is it good to merge?
> 
> @mkumatag Nothing pending form my end. It is good to merge

Thanks merging this as of now, will open a new if any further comments!

**Pull request merged**
