### PR TITLE
Update OVA generation code

### PR DESCRIPTION
**Pull request by bpradipt**

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/infra/pull/25#" title="Author self-approved">bpradipt</a>*

The full list of commands accepted by this bot can be found [here](?repo=ocp-power-automation%2Finfra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/infra/blob/master/OWNERS)~~ [bpradipt]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mkumatag** [comment]
/lgtm

code looks more cleaner now

/hold
It will be good if you can fix the author info it shows my name as that machine is configured with a global username and email with mine,

**Comment by ltccci** [comment]
New changes are detected. LGTM label has been removed.

**Comment by bpradipt** [comment]
@mkumatag updated it.. ptal

**Pull request merged**
