### PR TITLE
Stand-alone node creation powervs

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
- Initial code commit

Signed-off-by: Prajyot Parab <prajyot.parab@ibm.com>

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/infra/pull/7#" title="Author self-approved">Prajyot-Parab</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](?repo=ocp-power-automation%2Finfra).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ocp-power-automation/infra/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mkumatag** [comment]
I see a full-fledged TF code here! If this is a new project all together then prefer creating a new repo instead of adding into this repo, because this repo is just for adding some of the utility scripts for the infrastructure management.

**Comment by yussufsh** [comment]
You can might well as import the existing module https://github.com/ocp-power-automation/ocp4-upi-powervs/tree/master/modules/1_prepare. I see the same code duplicated here.

**Comment by Prajyot-Parab** [comment]
@mkumatag @yussufsh This is just to assist Rafael and Renata in their debugging of the grub issue (quick multi-node creation with fewer configs) as requested by Pradipta (there no specific future goal related to this at the moment)

**Comment by mkumatag** [comment]
> @mkumatag @yussufsh This is just to assist Rafael and Renata in their debugging of the grub issue (quick multi-node creation with fewer configs) as requested by Pradipta (there is no specific future goal related to this at the moment)

Okay.. can we import the existing code mentioned by the @yussufsh  to avoid the code duplication?

**Comment by yussufsh** [comment]
> Okay.. can we import the existing code mentioned by the @yussufsh to avoid the code duplication?

Right.. @Prajyot-Parab can import the module and use features needed at best using variables eg: `storage_type="none"`.

**Comment by bpradipt** [comment]
@yussufsh @mkumatag what do you think a good place for this ? This will be needed for generic PowerVS CI/CD as well..

**Comment by yussufsh** [comment]
IMO this place is fine.. I spoke with @Prajyot-Parab to make the code more simpler and resuable.

**Comment by mkumatag** [comment]
> IMO this place is fine.. I spoke with @Prajyot-Parab to make the code more simpler and resuable.

+1

**Comment by bpradipt** [comment]
@Prajyot-Parab let's complete this when you get some free time..

**Pull request closed without merging**
