### PR TITLE
Add the one time disk multipath resize service

### PR DESCRIPTION
**Pull request by mkumatag**
This fix is for https://bugs.launchpad.net/cloud-init/+bug/1556260

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ocp-power-automation/infra/pull/24#" title="Author self-approved">mkumatag</a>*

The full list of commands accepted by this bot can be found [here](?repo=ocp-power-automation%2Finfra).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ocp-power-automation/infra/blob/master/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mkumatag** [comment]
Adding hold for getting reviews from both the reviewers.

/hold

**Comment by mkumatag** [comment]
we have taken the other approach mentioned in #27 , hence closing this PR

**Pull request closed without merging**
